import { useState } from "react";
import { motion } from "framer-motion";

const MedicalDetails = () => {
  // State to manage which section is open
  const [activeSection, setActiveSection] = useState(null);

  // Sections data
  const sections = [
    {
      id: "upload",
      title: "Upload & Display Medical Details",
      description: "Securely upload and view your medical records, prescriptions, and test results.",
      content: (
        <div className="mt-6 p-6 bg-gray-50 rounded-lg">
          <h4 className="text-xl font-semibold mb-4">Upload Your Medical Records</h4>
          <p className="text-gray-600">
            Drag and drop your files or click to upload. Supported formats: PDF, JPEG, PNG.
          </p>
          <button className="mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors duration-300">
            Upload Files
          </button>
        </div>
      ),
    },
    {
      id: "summary",
      title: "AI-Generated Summary",
      description: "Get a concise summary of your health data generated by AI models.",
      content: (
        <div className="mt-6 p-6 bg-gray-50 rounded-lg">
          <h4 className="text-xl font-semibold mb-4">AI Summary</h4>
          <p className="text-gray-600">
            Your AI-generated health summary will appear here once processed.
          </p>
          <button className="mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors duration-300">
            Generate Summary
          </button>
        </div>
      ),
    },
    {
      id: "appointments",
      title: "Doctor Appointments & Medicinal Support",
      description: "Schedule appointments and get recommendations for medicinal support.",
      content: (
        <div className="mt-6 p-6 bg-gray-50 rounded-lg">
          <h4 className="text-xl font-semibold mb-4">Schedule an Appointment</h4>
          <p className="text-gray-600">
            Book an appointment with a doctor or get medicinal recommendations.
          </p>
          <button className="mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors duration-300">
            Book Now
          </button>
        </div>
      ),
    },
  ];

  return (
    <div className="container mx-auto p-4">
        {/* Text-Only Banner Section */}
        <motion.div
            initial={{ opacity: 0, y: -50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1 }}
            className="w-full text-center mb-12"
        >
            <motion.h2
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.5 }}
            className="text-5xl font-bold text-gray-900 mb-4"
            >
            Medical Details
            </motion.h2>
            <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 1 }}
            className="text-lg text-gray-600"
            >
            Manage your health records, AI summaries, and appointments in one place.
            </motion.p>
        </motion.div>

        {/* Navigation Section */}
        <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.5 }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
        >
            {sections.map((section) => (
            <motion.div
                key={section.id}
                whileHover={{ scale: 1.05 }}
                transition={{ duration: 0.3 }}
                className="p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 cursor-pointer"
                onClick={() => setActiveSection(activeSection === section.id ? null : section.id)}
            >
                <h3 className="text-xl font-bold mb-4">{section.title}</h3>
                <p className="text-gray-600">{section.description}</p>
            </motion.div>
            ))}
        </motion.div>

        {/* Active Section Content */}
        {activeSection && (
            <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="mt-8"
            >
            {sections.find((section) => section.id === activeSection)?.content}
            </motion.div>
        )}
        </div>
  );
};

export default MedicalDetails;